FROM lscr.io/linuxserver/qbittorrent:latest

# Copy VueTorrent to a standard location
COPY container/vuetorrent/public/ /opt/vuetorrent/

# Copy config with correct VueTorrent path
COPY container/defaults-vuetorrent/qBittorrent.conf /defaults/qBittorrent.conf
